### PR TITLE
Update/sso doc

### PR DESCRIPTION
**Pull request by JG1995**
Kristy asked me to make this guide a little more accesible and easily readable, would you give it a once-over to ensure everything still makes sense? It's not really major changes. It's mainly the SSO Configuration guide specifically.

### CODE REVIEW

**Review by MikaelElkiaer — APPROVED** [review]
@JG1995 Looks good to me. Could you also add a link  to the sso/index page? - I have no idea where this should be.

**Comment by JG1995** [comment]
@MikaelElkiaer I can, but it's already present in the sidebar when viewing this page - You think it would be beneficial to also have in the actual text?

**Comment by MikaelElkiaer** [comment]
@JG1995 I meant a link somewhere in the footer or whatever makes sense. Currently the page is only discoverable via a direct link or search.

**Comment by JG1995** [comment]
Oh, of course, my bad.

**Comment by JG1995** [comment]
@MikaelElkiaer added it to "Various" for now, but a larger restructure of the whole doc site is incoming within the next few sprints, so it'll be placed better soon

**Review by MikaelElkiaer — APPROVED** [review]

**Pull request merged**
